### ISSUE TITLE
能否通过图片实现轴的记录？

### ISSUE THREAD

**Issue by isaac1216** [SchneeHertz/sumimasen-makoto#1]
大佬你好，不知道这个项目还在不在维护，这个记轴网站精简又好用，但是通过文字记录轴不太方便，能不能加上上传图片的功能？

**Comment by isaac1216** [comment]
打包后的js文件有点大导致网页加载很慢，我根据网上教程配置了productionGzip，先安装依赖npm install --save-dev compression-webpack-plugin@1.1.12，修改vue.config.js的代码，修改后：
const CompressionWebpackPlugin = require('compression-webpack-plugin')
const productionGzipExtensions = ['js', 'css']
module.exports = {
  chainWebpack: config => {
    config
      .plugin('html')
      .tap(args => {
        args[0].title = '对不起，真琴'
        return args
      })
  },
  devServer: {
    proxy: 'http://localhost:8097'
  },
  productionSourceMap: false,
  configureWebpack: {
    plugins: [
      new CompressionWebpackPlugin({
      asset: '[path].gz[query]',
      algorithm: 'gzip',
      test: new RegExp('\\.(' + productionGzipExtensions.join('|') + ')$'),
      threshold: 10240,
      minRatio: 0.8
      })
    ]
  }
}

**Comment by SchneeHertz** [comment]
感谢建议，我已经配置了CompressionPlugin。
我之前没有考虑以图片的方式展示轴，是因为图片很难进行编辑，我们公会的轴都是从其他地方收集来的，经常会做调整，所以就不考虑用图片了，你可以试一下编辑轴界面的快速导入功能，那个编辑轴还是比较方便的（仅限文字）

> 大佬你好，不知道这个项目还在不在维护，这个记轴网站精简又好用，但是通过文字记录轴不太方便，能不能加上上传图片的功能？
